In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
df = pd.read_csv("fruit_data_with_colors.txt",delimiter = "\t")

FileNotFoundError: [Errno 2] No such file or directory: 'fruit_data_with_colors.txt'

In [ ]:
df.head()

In [5]:
X = df[["mass","width","height","color_score"]]

In [6]:
Y = df["fruit_label"]

In [7]:
trainX = np.array(X[:50])
trainY = np.array(Y[:50])
testX = np.array(X[50:])
testY = np.array(Y[50:])


In [18]:
class KNN:
    def __init__(self,k = 1):
        self.k = k
        
    def euclidian_distance(self,query,X):
        difference = np.array(X) - np.array(query)
        sqrd_diff = np.square(difference)
        sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
        distance = np.sqrt(sum_sqrd_diff)
        return distance
    
    def nearest_neighbours(self,distance):
        return np.argsort(distance)[:self.k]
    
    def predict(self,query,trainX,trainY):
        ed = self.euclidian_distance(query,trainX)
        nn = self.nearest_neighbours(ed)
        labels_nn = list(trainY[nn])
        return max(labels_nn, key = labels_nn.count) 
    

In [3]:
classifier = KNN(1)

NameError: name 'KNN' is not defined

In [20]:
predictions = [classifier.predict(x,trainX,trainY) for x in testX]

In [21]:
predictions

[4, 4, 4, 4, 4, 4, 4, 1, 4]

In [22]:
testY

array([4, 4, 4, 4, 4, 4, 4, 4, 4])

In [23]:
classifier = KNN(2)
predictions = [classifier.predict(x,trainX,trainY) for x in testX]
predictions

[4, 4, 4, 4, 4, 4, 4, 1, 4]

In [24]:
testY

array([4, 4, 4, 4, 4, 4, 4, 4, 4])

In [25]:
classifier = KNN(3)
predictions = [classifier.predict(x,trainX,trainY) for x in testX]
predictions

[4, 4, 4, 4, 4, 4, 4, 3, 4]

In [26]:
testY

array([4, 4, 4, 4, 4, 4, 4, 4, 4])

In [27]:
if __name__ == "__main__":
    print("hello")

hello


In [ ]:
from sklearn.metrics import confusion_matrix    #confusion Matrix
from sklearn import metrics
confusion_matrix(tainY, testY)


In [ ]:
from sklearn.metrics import accuracy_score    #accuracy
accuracy_score(tainY, testY, normalize=False)